# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            RGPR
tagline:          "R-package RGPR"
description:      'RGPR is a package for R to read, write, analyse and visualise ground-penetrating radar (GPR) data.'
url:              http://emanuelhuber.github.io/RGPR/
baseurl:          /RGPR

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.2

#github:
#  repo:           https://github.com/poole/hyde
