# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            RGPR
tagline:          "free software package for GPR data"
description:      'A free and open-source software package to read, write, analyse, process and visualise ground-penetrating radar (GPR) data.'
url:              https://emanuelhuber.github.io/RGPR/
baseurl:          /RGPR

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.2

#github:
#  repo:           https://github.com/poole/hyde
